language: cpp

git:
  submodules: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - g++-5
            - libboost1.55-dev
            - libboost-system1.55.0
            - libboost-program-options1.55.0
            - libboost-filesystem1.55.0
            - libboost-iostreams1.55.0
            - libboost-random1.55.0
            - libboost-iostreams1.55.0 
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5”


before_install:
    - eval "${MATRIX_EVAL}"

script:
  mkdir build && cd build && cmake ../src && make

