language: cpp

git:
  submodules: false

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-thread-dev
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"


before_install:
    - eval "${MATRIX_EVAL}"

script:
  pwd && sudo apt-cache search libboost && ls && mkdir build && cd build && cmake ../src && make

