language: cpp

git:
  submodules: false

matrix:
  include:
    addons:
      - os: linux
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - libboost-all-dev
        env: MATRIX_EVAL="export CC=gcc-4.9 && export CXX=g++-4.9"
      - os: linux
        apt:
          sources: ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
        env: MATRIX_EVAL="exoprt CC=gcc-5 && export CXX=g++-5"



before_install:
    - eval "${MATRIX_EVAL}"

script:
  mkdir build && cd build && cmake ../src && make && ./mosaic -—version

