language: cpp

git:
  submodules: false

matrix:
  include:

    # Linux gcc-4.9
    - os: linux
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - doxygen
            - libboost-all-dev
      env: 
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # Linux gcc-5
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - doxygen
            - libboost-all-dev
      env: 
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # Linux gcc-6
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - doxygen
            - libboost-all-dev
      env: 
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    - os: macos
      addons:

    # no Doxygen
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - libboost-all-dev
      env: 
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"


before_install:
    - eval "${MATRIX_EVAL}"

script:
  mkdir build && cd build && cmake ../src && make && "./mosaic -—version"

