language: cpp

git:
  submodules: false

os: 
  - linux

# Addons - with and without doxygen
addons:
  - apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.9
        - g++-5
        - libboost-all-dev
  - apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - g++-4.9
        - g++-5
        - libboost-all-dev
        - doxygen

env: 
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"

script:
  mkdir build && cd build && cmake -DCMAKE_CXX_COMPILER=$CXX ../src && make && ./mosaic -—version

