language: cpp

git:
  submodules: false

matrix:
  include:


    # OSX gcc-4.9
    - os: osx
      osx_image: xcode8
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      env:
        - E="CC=gcc-4.9 && CXX=g++-4.9"

    # OSX gcc-5
    - os: osx
      osx_image: xcode8
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      env:
        - E="brew install gcc5 && CC=gcc-5 && CXX=g++-5"

    # OSX gcc-6
    - os: osx
      osx_image: xcode8
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      env:
        - E="brew install gcc6 && CC=gcc-6 && CXX=g++-6"

    # OSX gcc-7
    - os: osx
      osx_image: xcode8
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      env:
        - E="brew install gcc && CC=gcc-7 && CXX=g++-7"

    # OSX clang
    - os: osx
      osx_image: xcode9
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      compiler: clang

    # OSX clang
    - os: osx
      osx_image: xcode8
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      compiler: clang

    # OSX clang
    - os: osx
      osx_image: xcode7.3
      before_install:
        brew update; brew install boost --c++11 --without-single --without-static 
      compiler: clang


before_install:
    - eval "${E}"

script:
  mkdir build && cd build && cmake ../src && make

